/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Registration.java
 *
 * Created on 24 Apr, 2021, 11:44:23 AM
 */

package package1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahil
 */
public class Registration extends javax.swing.JFrame {
    private boolean isDuplicate;
    private boolean phoneisNumeric;

    /** Creates new form Registration */
    public Registration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        register_password2 = new javax.swing.JTextField();
        register_mail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        register_password1 = new javax.swing.JTextField();
        register_gender_male = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        register_gender_female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        register_gender_other = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        register_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        register_phone = new javax.swing.JTextField();
        btn_gotologin = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration Form");

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 20));
        jLabel5.setText("Confirm Password:");

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 20));
        jLabel7.setText("Gender:");

        register_gender_male.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18));
        register_gender_male.setText("Male");
        register_gender_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_gender_maleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 20));
        jLabel3.setText("Email ID:");

        register_gender_female.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18));
        register_gender_female.setText("Female");
        register_gender_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_gender_femaleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 20));
        jLabel4.setText("Password:");

        register_gender_other.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18));
        register_gender_other.setText("Other");

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 20));
        jLabel2.setText("Name:");

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 20));
        jLabel6.setText("Phone:");

        btn_gotologin.setText("Go to Login");
        btn_gotologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gotologinActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/icons/signup.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_gotologin)
                                .addGap(35, 35, 35)
                                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(register_gender_male, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(register_gender_female)
                                .addGap(35, 35, 35)
                                .addComponent(register_gender_other, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(register_password2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(register_password1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(register_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(register_name, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(register_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(register_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(register_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(register_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(register_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(register_gender_male, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(register_gender_female, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(register_gender_other, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_gotologin)
                            .addComponent(btn_submit))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1038)/2, (screenSize.height-613)/2, 1038, 613);
    }// </editor-fold>//GEN-END:initComponents

    private Connection getDBConnection()
    {
       Connection con = null;
       try{
           Class.forName("com.mysql.jdbc.Driver");

       }catch(ClassNotFoundException ex){
           JOptionPane.showMessageDialog(this, ex);
       }

       try{
           con = (Connection) DriverManager.getConnection("jdbc:mysql:///tours","root","");
           return con;
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(this, ex);
       }
       return null;
    }

    public void reset(){
        register_name.setText("");
        register_mail.setText("");
        register_password1.setText("");
        register_password2.setText("");
        register_phone.setText("");
        register_gender_male.setSelected(false);
        register_gender_female.setSelected(false);
        register_gender_other.setSelected(false);
    }


    private void register_gender_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_gender_maleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_register_gender_maleActionPerformed

    private void register_gender_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_gender_femaleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_register_gender_femaleActionPerformed

    String name,mail,password,c_password,gender;
    String phone;


    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:

        name = register_name.getText();
        mail = register_mail.getText();
        password = register_password1.getText();
        c_password = register_password2.getText();
        phone = register_phone.getText();
        mail = register_mail.getText();

        if (register_gender_male.isSelected()){
            gender="Male";
            }
        else if(register_gender_female.isSelected()){
            gender="Female";
            }
        else{
            gender="Other";
            }

        String[] email= register_mail.getText().split("@");
        if(register_name.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a valid name");
         }
         else if(email.length==0){
            JOptionPane.showMessageDialog(this, "Invalid Email ID, please check");
         }
         else if(!register_password1.getText().equals(register_password2.getText())){
            JOptionPane.showMessageDialog(this, "Passwords don't match");
         }
         else if(register_password1.getText().length()<=6){
            JOptionPane.showMessageDialog(this, "Password must be at least of 6 characters");
         }
         else if(register_phone.getText().length()!=10){
            JOptionPane.showMessageDialog(this, "Please enter a 10 digit phone number");
         }
         else if(!(register_gender_male.isSelected() || register_gender_female.isSelected() ||
        register_gender_other.isSelected())){
            JOptionPane.showMessageDialog(this, "Please choose your gender");
         }
        else{
            try{
            Connection con = getDBConnection();
            PreparedStatement pst = (PreparedStatement)con.prepareStatement("insert into registration values(?,?,?,?,?,?)");
            pst.setString(1, name);
            pst.setString(2, mail);
            pst.setString(3, password);
            pst.setString(4, c_password);
            pst.setString(5, phone);
            pst.setString(6, gender);

            int row = pst.executeUpdate();
            con.close();

            reset();

        }catch(Exception ex){}
        }
        

    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_gotologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gotologinActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_gotologinActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_gotologin;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton register_gender_female;
    private javax.swing.JRadioButton register_gender_male;
    private javax.swing.JRadioButton register_gender_other;
    private javax.swing.JTextField register_mail;
    private javax.swing.JTextField register_name;
    private javax.swing.JTextField register_password1;
    private javax.swing.JTextField register_password2;
    private javax.swing.JTextField register_phone;
    // End of variables declaration//GEN-END:variables

}
